# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20180929_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=2)),
            ],
        ),
    ]
